# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-07-18T20:36:22+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import AnyUrl, AwareDatetime, BaseModel, Field, confloat, constr


class ChatRequest(BaseModel):
    session_id: str | None = Field(None, examples=['sess_abc123'])
    """
    ID de sesión existente. Si no se provee, se crea una nueva.
    """
    message: constr(min_length=1, max_length=4000) = Field(
        ..., examples=['¿Cómo configuro Vector Search?']
    )
    """
    Mensaje del usuario
    """
    stream: bool | None = True
    """
    Si true, responde vía SSE. Si false, respuesta completa en JSON.
    """


class Role(str, Enum):
    user = 'user'
    assistant = 'assistant'
    system = 'system'


class Citation(BaseModel):
    id: str = Field(..., examples=['cite_1'])
    title: str = Field(..., examples=['Vector Search Guide'])
    url: AnyUrl | None = Field(
        None, examples=['https://docs.databricks.com/vector-search']
    )
    snippet: str | None = None
    """
    Fragmento relevante del documento
    """
    relevance_score: confloat(ge=0.0, le=1.0) | None = None
    """
    Score de relevancia del documento
    """


class SessionSummary(BaseModel):
    id: str | None = None
    title: str | None = None
    message_count: int | None = None
    last_message_at: AwareDatetime | None = None


class Rating(        str, Enum):
    positive = 'positive'
    negative = 'negative'
    neutral = 'neutral'


class FeedbackRequest(BaseModel):
    message_id: str
    rating: Rating
    comment: constr(max_length=1000) | None = None


class Status(        str, Enum):
    registered = 'registered'


class FeedbackResponse(BaseModel):
    id: str | None = None
    status: Status | None = None


class Status1(        str, Enum):
    healthy = 'healthy'
    degraded = 'degraded'
    unhealthy = 'unhealthy'


class Databricks(        str, Enum):
    up = 'up'
    down = 'down'


class Dependencies(BaseModel):
    databricks: Databricks | None = None
    vector_search: Databricks | None = None


class HealthStatus(BaseModel):
    status: Status1 | None = None
    version: str | None = None
    dependencies: Dependencies | None = None


class Error(BaseModel):
    code: str = Field(..., examples=['INVALID_REQUEST'])
    """
    Código de error machine-readable
    """
    message: str
    """
    Mensaje descriptivo para el usuario
    """
    details: dict[str, Any] | None = None
    """
    Detalles adicionales del error
    """


class Message(BaseModel):
    id: str = Field(..., examples=['msg_xyz789'])
    role: Role
    content: str
    citations: list[Citation] | None = None
    """
    Fuentes RAG citadas (solo para assistant)
    """
    metadata: dict[str, Any] | None = None
    """
    Metadatos adicionales (tokens usados, latencia, etc.)
    """
    created_at: AwareDatetime


class Session(BaseModel):
    id: str
    title: str | None = None
    """
    Título auto-generado de la sesión
    """
    messages: list[Message]
    created_at: AwareDatetime
    updated_at: AwareDatetime | None = None


class SessionList(BaseModel):
    sessions: list[SessionSummary] | None = None
    total: int | None = None
    limit: int | None = None
    offset: int | None = None
