/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Enviar mensaje y recibir respuesta en streaming
         * @description Envía un mensaje al chatbot y recibe la respuesta vía Server-Sent Events.
         *     El stream incluye tokens, citas RAG y metadatos.
         */
        post: operations["createChatMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar sesiones del usuario */
        get: operations["listSessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example sess_abc123 */
                session_id: string;
            };
            cookie?: never;
        };
        /** Obtener sesión con historial completo */
        get: operations["getSession"];
        put?: never;
        post?: never;
        /** Eliminar sesión */
        delete: operations["deleteSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Enviar feedback sobre una respuesta
         * @description Permite al usuario calificar una respuesta del chatbot.
         *     Usado para evaluación continua del modelo (Mosaic AI Evaluation).
         */
        post: operations["submitFeedback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check del servicio */
        get: operations["healthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ChatRequest: {
            /**
             * @description ID de sesión existente. Si no se provee, se crea una nueva.
             * @example sess_abc123
             */
            session_id?: string;
            /**
             * @description Mensaje del usuario
             * @example ¿Cómo configuro Vector Search?
             */
            message: string;
            /**
             * @description Si true, responde vía SSE. Si false, respuesta completa en JSON.
             * @default true
             */
            stream: boolean;
        };
        Message: {
            /** @example msg_xyz789 */
            id: string;
            /** @enum {string} */
            role: "user" | "assistant" | "system";
            content: string;
            /** @description Fuentes RAG citadas (solo para assistant) */
            citations?: components["schemas"]["Citation"][];
            /** @description Metadatos adicionales (tokens usados, latencia, etc.) */
            metadata?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            created_at: string;
        };
        Citation: {
            /** @example cite_1 */
            id: string;
            /** @example Vector Search Guide */
            title: string;
            /**
             * Format: uri
             * @example https://docs.databricks.com/vector-search
             */
            url?: string;
            /** @description Fragmento relevante del documento */
            snippet?: string;
            /**
             * Format: float
             * @description Score de relevancia del documento
             */
            relevance_score?: number;
        };
        Session: {
            id: string;
            /** @description Título auto-generado de la sesión */
            title?: string;
            messages: components["schemas"]["Message"][];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at?: string;
        };
        SessionList: {
            sessions?: components["schemas"]["SessionSummary"][];
            total?: number;
            limit?: number;
            offset?: number;
        };
        SessionSummary: {
            id?: string;
            title?: string;
            message_count?: number;
            /** Format: date-time */
            last_message_at?: string;
        };
        FeedbackRequest: {
            message_id: string;
            /** @enum {string} */
            rating: "positive" | "negative" | "neutral";
            comment?: string;
        };
        FeedbackResponse: {
            id?: string;
            /** @enum {string} */
            status?: "registered";
        };
        HealthStatus: {
            /** @enum {string} */
            status?: "healthy" | "degraded" | "unhealthy";
            version?: string;
            dependencies?: {
                /** @enum {string} */
                databricks?: "up" | "down";
                /** @enum {string} */
                vector_search?: "up" | "down";
            };
        };
        Error: {
            /**
             * @description Código de error machine-readable
             * @example INVALID_REQUEST
             */
            code: string;
            /** @description Mensaje descriptivo para el usuario */
            message: string;
            /** @description Detalles adicionales del error */
            details?: {
                [key: string]: unknown;
            };
        };
    };
    responses: {
        /** @description Petición inválida */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "INVALID_REQUEST",
                 *       "message": "El mensaje no puede estar vacío"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description No autenticado o token inválido */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "UNAUTHORIZED",
                 *       "message": "Token JWT inválido o expirado"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Recurso no encontrado */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "NOT_FOUND",
                 *       "message": "La sesión no existe"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Límite de peticiones excedido */
        RateLimited: {
            headers: {
                "X-RateLimit-Limit"?: number;
                "X-RateLimit-Remaining"?: number;
                "X-RateLimit-Reset"?: number;
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "RATE_LIMITED",
                 *       "message": "Has excedido el límite de 60 peticiones por minuto"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Error en servicio upstream (Databricks) */
        UpstreamError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "UPSTREAM_ERROR",
                 *       "message": "El servicio de IA no está disponible"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Respuesta bloqueada por filtro de seguridad */
        ContentFiltered: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "CONTENT_FILTERED",
                 *       "message": "La respuesta fue bloqueada por políticas de seguridad"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createChatMessage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "session_id": "sess_abc123",
                 *       "message": "¿Cómo configuro Vector Search en Databricks?",
                 *       "stream": true
                 *     }
                 */
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Stream SSE iniciado correctamente */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example event: thinking
                     *     data: {"content": "Buscando en documentación de Databricks..."}
                     *
                     *     event: citation
                     *     data: {"id": "cite_1", "title": "Vector Search Guide", "url": "https://docs.databricks.com/vector-search", "snippet": "Vector Search permite..."}
                     *
                     *     event: token
                     *     data: {"content": "Para configurar"}
                     *
                     *     event: token
                     *     data: {"content": " Vector Search..."}
                     *
                     *     event: done
                     *     data: {"message_id": "msg_xyz789", "usage": {"prompt_tokens": 150, "completion_tokens": 89}}
                     */
                    "text/event-stream": string;
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimited"];
            502: components["responses"]["UpstreamError"];
            503: components["responses"]["ContentFiltered"];
        };
    };
    listSessions: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de sesiones */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example sess_abc123 */
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sesión con mensajes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example sess_abc123 */
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sesión eliminada */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    submitFeedback: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "message_id": "msg_xyz789",
                 *       "rating": "positive",
                 *       "comment": "Respuesta muy clara y con buenas citas"
                 *     }
                 */
                "application/json": components["schemas"]["FeedbackRequest"];
            };
        };
        responses: {
            /** @description Feedback registrado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Servicio operativo */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
}
